# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'SocialSharing' do
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'Fabric'
	pod ‘TwitterKit’
	pod ’TwitterCore’

end

target 'SocialSharingTests' do

end

