# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'SocialSharing' do
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'Fabric'
	pod ‘TwitterKit’
	pod ’TwitterCore’
	pod ‘Google’
	pod ‘Google/SignIn’
	pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
    	pod 'GTMOAuth2', '~> 1.1.0'

end

target 'SocialSharingTests' do

end

